version: '3.8'



services:

  nginx:

    image: nginx:alpine

    ports:

      - "80:80"

    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:

      - django-grafana

    networks:

      - app-network



  django-grafana:

    build: 

      context: ./docs-django-grafana

      dockerfile: Dockerfile

    deploy:

      replicas: 5

      update_config:

        parallelism: 2

        delay: 10s

      restart_policy:

        condition: on-failure

    networks:

      - app-network



  django-react:

    build: ./docs-django-react

    networks:

      - app-network



  flask-stripe:

    build: ./ecommerce-flask-stripe

    networks:

      - app-network



  flask-softui:

    build: ./flask-soft-ui-design

    networks:

      - app-network



  rocket-ecommerce:

    build: ./rocket-ecommerce

    ports:

      - "8080:8080"  # Accès direct sans reverse proxy

    networks:

      - app-network



networks:

  app-network:

    driver: bridge
